/**
 * generators.js
 *
 * Produces two editable starting artefacts from the scanned page:
 *  - a schema.org JSON-LD scaffold (Organization + WebSite)
 *  - a draft llms.txt following the Answer.AI convention
 *
 * These are deliberately conservative scaffolds, not finished output.
 * The README is explicit that a human must review and complete them
 * (especially sameAs and the disambiguation fields).
 */

export function generateSchema({ $, finalUrl }) {
  let origin = finalUrl;
  try {
    origin = new URL(finalUrl).origin;
  } catch {
    /* keep as-is */
  }
  const title =
    ($('meta[property="og:title"]').attr('content') ||
      $('title').first().text() ||
      'Your Organization').trim();
  const desc =
    ($('meta[name="description"]').attr('content') ||
      $('meta[property="og:description"]').attr('content') ||
      '').trim();

  const org = {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: title.split('—')[0].split('|')[0].trim(),
    url: origin,
    description: desc || 'TODO: one-sentence factual description.',
    logo: `${origin}/logo.png`,
    sameAs: [
      'TODO: https://www.wikidata.org/wiki/Q...',
      'TODO: https://www.linkedin.com/company/...',
      'TODO: https://www.crunchbase.com/organization/...',
      'TODO: https://github.com/...',
    ],
    founder: {
      '@type': 'Person',
      name: 'TODO: Founder Name',
      url: origin,
    },
  };

  return JSON.stringify(org, null, 2);
}

export function generateLlmsTxt({ $, finalUrl }) {
  let origin = finalUrl;
  try {
    origin = new URL(finalUrl).origin;
  } catch {
    /* keep */
  }
  const name = ($('title').first().text() || 'Your Project')
    .split('—')[0]
    .split('|')[0]
    .trim();
  const desc =
    ($('meta[name="description"]').attr('content') || '').trim() ||
    'TODO: one-paragraph summary of what this project is and who runs it.';

  // Mine a few internal links as candidate "Core" entries.
  const links = [];
  $('a[href]').each((_, el) => {
    const href = $(el).attr('href') || '';
    const text = ($(el).text() || '').trim();
    if (
      text &&
      text.length > 2 &&
      text.length < 60 &&
      (href.startsWith('/') || href.startsWith(origin)) &&
      !href.includes('#') &&
      links.length < 6
    ) {
      const abs = href.startsWith('/') ? origin + href : href;
      if (!links.find((l) => l.abs === abs)) links.push({ text, abs });
    }
  });

  let out = `# ${name}\n\n`;
  out += `> ${desc}\n\n`;
  out += `## Core\n`;
  if (links.length) {
    for (const l of links) out += `- [${l.text}](${l.abs}): TODO describe this page.\n`;
  } else {
    out += `- [About](${origin}/about): TODO company background, team, mission.\n`;
    out += `- [Product](${origin}/product): TODO what it does and how.\n`;
  }
  out += `\n## Optional\n`;
  out += `- [Press & recognition](${origin}/press): TODO independent coverage.\n`;
  out += `\n<!-- Generated by @kirkelabs/ai-legibility-scan. Review and edit before publishing. -->\n`;
  return out;
}
